### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by minhnimble** [ducbm051291/NimbleSurvey#3]
As you can probably see, the surveys list API should be capable of providing more data than you have currently displayed. It would be nice if we could paginate those data by using some kind of user inputs (swipe to the end to load more, add load next page button, etc.). What do you think?

**Comment by ducbm051291** [comment]
Yes, there's should be load more. Currently, I hard code page 1 and size 10. I did prepare loading more feature but I see that the challenge doesn't require it so I skip it ^^

**Comment by minhnimble** [comment]
Oh this is actually an optional requirement from the challenge, as it would be great for us to additionally see what is your capability on handling pagination loading. But yeah, there definitely should be a balance in engineering effort, technical debt and ease of throwing out code. We all trade one constraints for another, one set of assumptions with other. 👍

**Comment by minhnimble** [comment]
Looks good to me on the pagination logic 👍
