### ISSUE TITLE
Environment issues

### ISSUE THREAD

**Issue by minhnimble** [ducbm051291/NimbleSurvey#4]
As per our our API [documentation](https://github.com/nimblehq/nimble-survey-web/wiki/REST-API#ios), there are more environments that our API should be able to support, which are Staging and Production, and you only handled the Production environment so far. I would like to know more on if you have any experiences in handling the CI/CD for different environments and if yes, how can CI/CD help us in such cases?

At the same time, it would be great if you could update the project implementation to handle both environments and point to the correct base endpoint for each environment as well. What do you think?

**Comment by ducbm051291** [comment]
Actually, I dont' have much experience about CI/CD. Currently, I just use fastlane to deploy build to firebase, testflight but sure I did configure environment using enum type in my work. Because this is just a challenge so I keep it simple in Constants
