### ISSUE TITLE
Unable to refresh token issue

### ISSUE THREAD

**Issue by minhnimble** [ducbm051291/NimbleSurvey#7]
When I leave the phone logged in with previous session and wait until the token expires, entering the application again will cause it to prompt an error and user was unable to use the application anymore. Please investigate and let me know why this problem occurs. At the same time, how do you intent to fix this issue?

https://user-images.githubusercontent.com/70877098/158935238-b413c391-8f3f-4428-ae1d-9c766fb9a48a.mov

**Comment by ducbm-belive** [comment]
I think it's because of the fixed of id 👍  I will check this tonight

**Comment by minhnimble** [comment]
It works now 👍
